version: "3.8"

services:

  communal-services-db:
    container_name: communal-services-db
    image: postgres:${POSTGRES_PORT}
    restart: on-failure
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "${DATABASE_PORT}:5432"

  keycloak-db:
    container_name: keycloak-db
    image: postgres:14.0
    volumes:
      - keycloak_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${KEYCLOAK_DATABASE_NAME}
      - POSTGRES_USER=${KEYCLOAK_DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${KEYCLOAK_DATABASE_PASSWORD}
    ports:
      - "${KEYCLOAK_DATABASE_PORT}:5432"

  keycloak:
    container_name: keycloak
    image: bitnami/keycloak:22.0.4
    environment:
      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASSWORD=260
      - KEYCLOAK_MANAGEMENT_PASSWORD=260
      - KEYCLOAK_DATABASE_PORT=${KEYCLOAK_DATABASE_PORT}
      - KEYCLOAK_DATABASE_HOST=${KEYCLOAK_DATABASE_HOST}
      - KEYCLOAK_DATABASE_NAME=${KEYCLOAK_DATABASE_NAME}
      - KEYCLOAK_CREATE_ADMIN_USER='true'
      - KEYCLOAK_DATABASE_USER=${KEYCLOAK_DATABASE_USERNAME}
      - KEYCLOAK_DATABASE_PASSWORD=${KEYCLOAK_DATABASE_PASSWORD}
    ports:
      - "${KEYCLOAK_PORT}:8080"
    depends_on:
      - keycloak-db

volumes:
  db:
  keycloak_db: