version: "3.8"

services:

  communal-services-db:
    container_name: communal-services-db
    image: postgres:14.0
    restart: on-failure
    environment:
      - POSTGRES_DB=communal-services
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "55432:5432"

volumes:
  db: