spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:55432/communal-services
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
  messages:
    basename: i18n/messages
    encoding: UTF-8